baseURL = 'http:s://arnn5115.github.io/arnn5115'
languageCode = 'id'
title = 'Tech & Physic Stuff | ARNN5115's Blog'
theme = "PaperMod"

[params]
  author = "Andika R. N. Nugraha"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/arnn5115"

  [[params.social]]
    icon = "instagram"
    name = "Instagram"
    url = "https://instagram.com/arnn5115"
